version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile
    networks:
      - app-network
    ports:
      - "90:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://db_user:db_password@db:5432/db_name

  frontend:
    build:
      context: ./frontend/
    networks:
      - app-network
    ports:
      - "8080:8080"

  db:
    image: postgres
    networks:
      - app-network
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_password
      - POSTGRES_DB=db_name


  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app-network
    depends_on:
      - backend
      - frontend

networks:
  app-network: